# version: '2.12.2'
# services:
#   backend:
#     image: superjaehun/back
#     container_name: back
#     build:
#       context: ./BackEnd
#       dockerfile: Dockerfile
#     ports:
#       - "9002:8080"  # 호스트 포트 번호(컨테이너 외부): 컨테이너 포트 번호(컨테이너 내부)
#     environment:
#       - SPRING_PROFILES_ACTIVE=prod
#     restart: always

#   mysql:
#     image: mysql:8.0.35
#     container_name: mysql
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=c103103
#       - MYSQL_DATABASE=weeting
#       - TZ=Asia/Seoul
#     command:
#       - --character-set-server=utf8mb4
#       - --collation-server=utf8mb4_unicode_ci
#     volumes:
#       - db-data:/var/lib/mysql
#     restart: always

# volumes:
#   db-data:
