version: '2.27.0'

services:
  frontend:
    image: superjaehun/front
    container_name: front
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "9003:3000"
    depends_on:
      - backend

  backend:
    image: superjaehun/back
    container_name: back
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
