version: '3'
services:
  back:
    image: superjaehun/back:latest
    ports:
      - "9002:8080"
    depends_on:
      - redis
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/weeting?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: c103103
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: c103103

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass c103103

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: weeting
      MYSQL_ROOT_PASSWORD: c103103
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: