version: '3.8'
services:
  back:
    image: ${DOCKERHUB_REGISTRY}
    ports:
      - "9002:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: c103103

  front:
    container_name: superjaehun_front 
    build:
      context: ../FrontEnd
      dockerfile: Dockerfile
    ports:
      - "9003:3000"
    depends_on:
      - back

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass c103103

volumes:
  mysql_data: