version: '3.8'
services:
  back:
    container_name: back 
    networks:
      - weeting-network
    image: ${DOCKERHUB_REGISTRY}
    ports:
      - "9002:8080"
    depends_on:
      - redis
      - mysql

  front:
    networks:
      - weeting-network
    container_name: front 
    build:
      context: ../FrontEnd
      dockerfile: Dockerfile
    ports:
      - "9003:3000"
    depends_on:
      - back

  redis:
    container_name: redis
    volumes:
      - ~/redis/data:/data
    user: root
    networks:
      - weeting-network
    image: redis:alpine
    ports:
      - "6379:6379"

  mysql:
    networks:
      - weeting-network
    image: mysql:latest
    environment:
      MYSQL_DATABASE: weeting
      MYSQL_ROOT_PASSWORD: c103103
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  weeting-network:
    external: true