import { RoomInfo } from '../types/game';

export const RoomListData: RoomInfo[] = [
  {
    roomMode: 'rank',
    roomId: '1',
    roomName: '첫 번째 방',
    roomStatus: 'waiting',
    roomForbiddentime: null,
    roomEndtime: null,
    roomSubject: 'aaaa',
    roomMaxCnt: 6,
    roomUsers: [
      {
        userId: 'm1',
        nickname: 'Player1',
        outfit: 'outfit1',
        ready: false,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm2',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm3',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'normal',
    roomId: '2',
    roomName: '두 번째 방',
    roomStatus: 'start',
    roomForbiddentime: null,
    roomEndtime: null,
    roomSubject: 'aaaa',
    roomMaxCnt: 6,
    roomUsers: [
      {
        userId: 'm3',
        nickname: 'Player3',
        outfit: 'outfit3',
        ready: true,
        word: null,
        score: 50,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'rank',
    roomId: '3',
    roomName: '세 번째 방',
    roomStatus: 'allready',
    roomForbiddentime: null,
    roomEndtime: null,
    roomSubject: 'aaaa',
    roomMaxCnt: 8,
    roomUsers: [
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'normal',
    roomId: '4',
    roomName: '네 번째 방',
    roomStatus: 'end',
    roomForbiddentime: '2024-05-01T12:00:00',
    roomEndtime: '2024-05-01T12:30:00',
    roomSubject: 'aaaa',
    roomMaxCnt: 8,
    roomUsers: [
      {
        userId: 'm6',
        nickname: 'Player6',
        outfit: 'outfit6',
        ready: false,
        word: null,
        score: 70,
        isAlive: true,
      },
      {
        userId: 'm7',
        nickname: 'Player7',
        outfit: 'outfit7',
        ready: false,
        word: null,
        score: 95,
        isAlive: true,
      },
      {
        userId: 'm8',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
      {
        userId: 'm8',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
    ],
  },
];
