import { RoomWaitInfo } from './room';

export const RoomWaitData: RoomWaitInfo[] = [
  {
    roomMode: 'rank',
    roomId: '1',
    roomName: '첫 번째 방',
    roomStatus: 'waiting',
    roomMaxCnt: 6,
    roomPassword: 1541,
    roomUsers: [
      {
        userId: 'm1',
        nickname: 'Player1',
        outfit: 'outfit1',
        ready: false,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm2',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm3',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'normal',
    roomId: '2',
    roomName: '두 번째 방',
    roomStatus: 'start',
    roomMaxCnt: 6,
    roomPassword: 1541,
    roomUsers: [
      {
        userId: 'm3',
        nickname: 'Player3',
        outfit: 'outfit3',
        ready: true,
        word: null,
        score: 50,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
        isAlive: true,
      },
      {
        userId: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'rank',
    roomId: '3',
    roomName: '세 번째 방',
    roomStatus: 'allready',
    roomMaxCnt: 8,
    roomPassword: null,
    roomUsers: [
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
      {
        userId: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'normal',
    roomId: '4',
    roomName: '네 번째 방',
    roomStatus: 'end',
    roomMaxCnt: 8,
    roomPassword: null,
    roomUsers: [
      {
        userId: 'm6',
        nickname: 'Player6',
        outfit: 'outfit6',
        ready: false,
        word: null,
        score: 70,
        isAlive: true,
      },
      {
        userId: 'm7',
        nickname: 'Player7',
        outfit: 'outfit7',
        ready: false,
        word: null,
        score: 95,
        isAlive: true,
      },
      {
        userId: 'm8',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
      {
        userId: 'm8',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'normal',
    roomId: '5',
    roomName: '다섯 번째 방',
    roomStatus: 'end',
    roomMaxCnt: 8,
    roomPassword: null,
    roomUsers: [
      {
        userId: 'm9',
        nickname: 'Player6',
        outfit: 'outfit6',
        ready: false,
        word: null,
        score: 70,
        isAlive: true,
      },
      {
        userId: 'm10',
        nickname: 'Player7',
        outfit: 'outfit7',
        ready: false,
        word: null,
        score: 95,
        isAlive: true,
      },
      {
        userId: 'm11',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
      {
        userId: 'm12',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'normal',
    roomId: '6',
    roomName: '여섯 번째 방',
    roomStatus: 'end',
    roomMaxCnt: 8,
    roomPassword: null,
    roomUsers: [
      {
        userId: 'm13',
        nickname: 'Player6',
        outfit: 'outfit6',
        ready: false,
        word: null,
        score: 70,
        isAlive: true,
      },
      {
        userId: 'm14',
        nickname: 'Player7',
        outfit: 'outfit7',
        ready: false,
        word: null,
        score: 95,
        isAlive: true,
      },
      {
        userId: 'm15',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
      {
        userId: 'm16',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
    ],
  },
  {
    roomMode: 'normal',
    roomId: '6',
    roomName: '일곱 번째 방',
    roomStatus: 'end',
    roomMaxCnt: 8,
    roomPassword: null,
    roomUsers: [
      {
        userId: 'm19',
        nickname: 'Player6',
        outfit: 'outfit6',
        ready: false,
        word: null,
        score: 70,
        isAlive: true,
      },
      {
        userId: 'm20',
        nickname: 'Player7',
        outfit: 'outfit7',
        ready: false,
        word: null,
        score: 95,
        isAlive: true,
      },
      {
        userId: 'm21',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
      {
        userId: 'm22',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
        isAlive: true,
      },
    ],
  },
];
