import { RoomInfo } from '../types/game';

export const RoomListData: RoomInfo[] = [
  {
    roommode: 'rank',
    roomid: '1',
    roomname: '첫 번째 방',
    roomstatus: 'waiting',
    roomforbiddentime: null,
    roomendtime: null,
    roommaxcnt: 6,
    roommembers: [
      {
        memberid: 'm1',
        nickname: 'Player1',
        outfit: 'outfit1',
        ready: false,
        word: null,
        score: 0,
      },
      {
        memberid: 'm2',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
      },
      {
        memberid: 'm3',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
      },
      {
        memberid: 'm4',
        nickname: 'Player2',
        outfit: 'outfit2',
        ready: false,
        word: null,
        score: 0,
      },
    ],
  },
  {
    roommode: 'normal',
    roomid: '2',
    roomname: '두 번째 방',
    roomstatus: 'start',
    roomforbiddentime: null,
    roomendtime: null,
    roommaxcnt: 6,
    roommembers: [
      {
        memberid: 'm3',
        nickname: 'Player3',
        outfit: 'outfit3',
        ready: true,
        word: null,
        score: 50,
      },
      {
        memberid: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
      },
      {
        memberid: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
      },
      {
        memberid: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
      },
      {
        memberid: 'm4',
        nickname: 'Player4',
        outfit: 'outfit4',
        ready: true,
        word: null,
        score: 30,
      },
    ],
  },
  {
    roommode: 'rank',
    roomid: '3',
    roomname: '세 번째 방',
    roomstatus: 'allready',
    roomforbiddentime: null,
    roomendtime: null,
    roommaxcnt: 8,
    roommembers: [
      {
        memberid: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
      },
      {
        memberid: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
      },
      {
        memberid: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
      },
      {
        memberid: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
      },
      {
        memberid: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
      },
      {
        memberid: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
      },
      {
        memberid: 'm5',
        nickname: 'Player5',
        outfit: 'outfit5',
        ready: true,
        word: null,
        score: 0,
      },
    ],
  },
  {
    roommode: 'normal',
    roomid: '4',
    roomname: '네 번째 방',
    roomstatus: 'end',
    roomforbiddentime: '2024-05-01T12:00:00',
    roomendtime: '2024-05-01T12:30:00',
    roommaxcnt: 8,
    roommembers: [
      {
        memberid: 'm6',
        nickname: 'Player6',
        outfit: 'outfit6',
        ready: false,
        word: null,
        score: 70,
      },
      {
        memberid: 'm7',
        nickname: 'Player7',
        outfit: 'outfit7',
        ready: false,
        word: null,
        score: 95,
      },
      {
        memberid: 'm8',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
      },
      {
        memberid: 'm8',
        nickname: 'Player8',
        outfit: 'outfit8',
        ready: false,
        word: null,
        score: 80,
      },
    ],
  },
];
